### ISSUE TITLE
Create a test for reimport of transactional data

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#140]
Related to #139 

Implement test for: 
-reimport of opening
-reimport of actual
-reimport of cashflow

**Comment by sbusato** [comment]
Use case1:
Consider a data node at inception, create openings for this data node and import the file multiple times.
=> the result should not change.

Use case2:
Consider one data node at inception and one that is not. Create an Actuals file that contains data for both these two data nodes. Import this file multiple times.
=> the result should not change.

Use case3:
Consider one GRIC that is linked to one GIC. The GRIC already existed the previous year, while the GIC is at inception.
Import data for the GRIC in the previous period.
Import Openings for the GIC in the current period.
Import Cashflows for the GRIC in the current period.

@dcolleoni

**Comment by amuolo** [comment]
@dcolleoni @sbusato who is working on this ticket?

**Comment by tkukuljan** [comment]
Please contact me if you start working on this ticket, as I already did some work.

**Comment by nnikolopoulos** [comment]
Examination of the case: 
<HR>
Import Cashflow for GRIC [previous period] → Import Opening for GIC [current period] → Import Cashflow for GRIC [current period]
<HR>

Yielded that upon the import of the Openings, ifrs variables for the linked Reinsurace for the previous period exist in the `identities` dictionary but **not** in the `ivs` var: 

<img width="1312" alt="MicrosoftTeams-image" src="https://github.com/Systemorph/IFRS17CalculationEngine/assets/114566025/ee194eb6-50ab-4f15-8fc4-14564100de9e">

Consequently no IfrsVars are created for the linked Reinsurance when Openings are imported for the GIC.
 
It looks like the reason is that estimate type "BE" appears in scopes `PvCurrent` and `PvLocked` which not are concatenated in the `ComputeIfrsVarsOpenigs` like they are for `ComputeIfrsVarsCashflows`.

 
<img width="1119" alt="MicrosoftTeams-image (1)" src="https://github.com/Systemorph/IFRS17CalculationEngine/assets/114566025/2adcec0b-a716-40ae-8e61-92012df9d9d7">

Is this behavior expected?

FYI: @dcolleoni, @amuolo and @sbusato

**Comment by nnikolopoulos** [comment]
The remaining cases (i.e. use case III and IV) which have been documented in this issue and have not been treated are being tracked in issue #347.
