### ISSUE TITLE
Scenario improvements from PR #232

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#234]
See comments to PR #232 
1. Create a Scenario Class with all these consts inside without hardcoding
2. Consider using ToStringWith instead of ToIdentityString to increase performance. Be aware that different clients might have different IP for reportVariables

**Comment by amuolo** [comment]
The ToIdentityString and the TotringWith methods do the same except for the former being slow due to reflection being used. Now it is not clear why we keep both in the CE and it is even confusing. I suggest we keep only one that takes the id props from a reflection code that executes only once and then caches the list. We can name this method "ToIdentityString" because it is the best name among the two above. 

@tkukuljan @dcolleoni

**Comment by amuolo** [comment]
The final unique method to retrieve a string from the list of id props should have a parameter to give the possibility to exclude given props. I suggest to call the parameter "ignoreProperties", so that the API would read like this:

myInstance.ToIdentityString( ignoreProperties: new[]{ IfrsVariable.AocType } )

@tkukuljan @dcolleoni
