### ISSUE TITLE
Projection data model - use double[] in IfrsVariable

### ISSUE THREAD

**Issue by dcolleoni** [Systemorph/IFRS17CalculationEngine#247]
is it better to use double[] or multiple variables with double prop?

**Comment by andrey-katz-systemorph** [comment]
OK, maybe it is time to summarize some of my observations on this point. In fact, we should better organize the Values in an array at the level of the IfrsVariable already. The reason is that ReportVariable already has an integer dimension Projection. At the level of report it is simple to keep one value and change the projection value between 0 and 12  for each Value#. Then slicing and filtering by projection becomes natural in the reports. In order to populate the report variable this way we can either introduce an integer dimension for projection already in the IfrsVariable or alternatively organize them in an array. In fact, to get reasonable report with dimensions I combined all the projections into a singe array and populated the ReportVariable. Anyway, these are two options that I see and we should decide which way we go.

FYI @dcolleoni

**Comment by dcolleoni** [comment]
Closing this issue as the PR is completed.
